// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user

import (
	"context"

	"github.com/1348453525/user-redeem-code-gozero/user-rpc/proto/user"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserListRequest  = user.GetUserListRequest
	GetUserListResponse = user.GetUserListResponse
	IDRequest           = user.IDRequest
	LoginRequest        = user.LoginRequest
	LoginResponse       = user.LoginResponse
	RegisterRequest     = user.RegisterRequest
	UpdateUserRequest   = user.UpdateUserRequest
	UserInfoResponse    = user.UserInfoResponse

	User interface {
		// 注册
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		// 登录
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 获取用户信息
		Info(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		// 获取用户列表
		GetList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error)
		// 更新用户信息
		Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// 删除用户
		Delete(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 登录
func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUser) Info(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Info(ctx, in, opts...)
}

// 获取用户列表
func (m *defaultUser) GetList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultUser) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 删除用户
func (m *defaultUser) Delete(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
