// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: redeem_code.proto

package server

import (
	"context"

	"github.com/1348453525/user-redeem-code-gozero/redeem-code-rpc/internal/logic"
	"github.com/1348453525/user-redeem-code-gozero/redeem-code-rpc/internal/svc"
	"github.com/1348453525/user-redeem-code-gozero/redeem-code-rpc/redeemcode"
	"google.golang.org/protobuf/types/known/emptypb"
)

type RedeemCodeServer struct {
	svcCtx *svc.ServiceContext
	redeemcode.UnimplementedRedeemCodeServer
}

func NewRedeemCodeServer(svcCtx *svc.ServiceContext) *RedeemCodeServer {
	return &RedeemCodeServer{
		svcCtx: svcCtx,
	}
}

// 创建兑换码批次
func (s *RedeemCodeServer) CreateRedeemCodeBatch(ctx context.Context, in *redeemcode.CreateRedeemCodeBatchRequest) (*redeemcode.RedeemCodeBatchResponse, error) {
	l := logic.NewCreateRedeemCodeBatchLogic(ctx, s.svcCtx)
	return l.CreateRedeemCodeBatch(in)
}

// 获取兑换码批次详情
func (s *RedeemCodeServer) RedeemCodeBatchDetail(ctx context.Context, in *redeemcode.IDRequest) (*redeemcode.RedeemCodeBatchResponse, error) {
	l := logic.NewRedeemCodeBatchDetailLogic(ctx, s.svcCtx)
	return l.RedeemCodeBatchDetail(in)
}

// 获取兑换码批次列表
func (s *RedeemCodeServer) GetRedeemCodeBatchList(ctx context.Context, in *redeemcode.GetListRequest) (*redeemcode.GetRedeemCodeBatchListResponse, error) {
	l := logic.NewGetRedeemCodeBatchListLogic(ctx, s.svcCtx)
	return l.GetRedeemCodeBatchList(in)
}

// 更新兑换码批次
func (s *RedeemCodeServer) UpdateRedeemCodeBatch(ctx context.Context, in *redeemcode.UpdateRedeemCodeBatchRequest) (*emptypb.Empty, error) {
	l := logic.NewUpdateRedeemCodeBatchLogic(ctx, s.svcCtx)
	return l.UpdateRedeemCodeBatch(in)
}

// 删除兑换码批次
func (s *RedeemCodeServer) DeleteRedeemCodeBatch(ctx context.Context, in *redeemcode.IDRequest) (*emptypb.Empty, error) {
	l := logic.NewDeleteRedeemCodeBatchLogic(ctx, s.svcCtx)
	return l.DeleteRedeemCodeBatch(in)
}

// 获取兑换码详情
func (s *RedeemCodeServer) RedeemCodeDetail(ctx context.Context, in *redeemcode.IDRequest) (*redeemcode.RedeemCodeResponse, error) {
	l := logic.NewRedeemCodeDetailLogic(ctx, s.svcCtx)
	return l.RedeemCodeDetail(in)
}

// 获取兑换码列表
func (s *RedeemCodeServer) GetRedeemCodeList(ctx context.Context, in *redeemcode.GetListRequest) (*redeemcode.GetRedeemCodeListResponse, error) {
	l := logic.NewGetRedeemCodeListLogic(ctx, s.svcCtx)
	return l.GetRedeemCodeList(in)
}

// 更新兑换码
func (s *RedeemCodeServer) UpdateRedeemCode(ctx context.Context, in *redeemcode.UpdateRedeemCodeRequest) (*emptypb.Empty, error) {
	l := logic.NewUpdateRedeemCodeLogic(ctx, s.svcCtx)
	return l.UpdateRedeemCode(in)
}

// 删除兑换码
func (s *RedeemCodeServer) DeleteRedeemCode(ctx context.Context, in *redeemcode.IDRequest) (*emptypb.Empty, error) {
	l := logic.NewDeleteRedeemCodeLogic(ctx, s.svcCtx)
	return l.DeleteRedeemCode(in)
}

// 使用兑换码
func (s *RedeemCodeServer) UseRedeemCode(ctx context.Context, in *redeemcode.UseRedeemCodeRequest) (*emptypb.Empty, error) {
	l := logic.NewUseRedeemCodeLogic(ctx, s.svcCtx)
	return l.UseRedeemCode(in)
}
