// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: redeem_code.proto

package redeemcodeclient

import (
	"context"

	"github.com/1348453525/user-redeem-code-gozero/redeem-code-rpc/redeemcode"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRedeemCodeBatchRequest   = redeemcode.CreateRedeemCodeBatchRequest
	GetListRequest                 = redeemcode.GetListRequest
	GetRedeemCodeBatchListResponse = redeemcode.GetRedeemCodeBatchListResponse
	GetRedeemCodeListResponse      = redeemcode.GetRedeemCodeListResponse
	IDRequest                      = redeemcode.IDRequest
	RedeemCodeBatchResponse        = redeemcode.RedeemCodeBatchResponse
	RedeemCodeResponse             = redeemcode.RedeemCodeResponse
	UpdateRedeemCodeBatchRequest   = redeemcode.UpdateRedeemCodeBatchRequest
	UpdateRedeemCodeRequest        = redeemcode.UpdateRedeemCodeRequest
	UseRedeemCodeRequest           = redeemcode.UseRedeemCodeRequest

	RedeemCode interface {
		// 创建兑换码批次
		CreateRedeemCodeBatch(ctx context.Context, in *CreateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error)
		// 获取兑换码批次详情
		RedeemCodeBatchDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error)
		// 获取兑换码批次列表
		GetRedeemCodeBatchList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeBatchListResponse, error)
		// 更新兑换码批次
		UpdateRedeemCodeBatch(ctx context.Context, in *UpdateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// 删除兑换码批次
		DeleteRedeemCodeBatch(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// 获取兑换码详情
		RedeemCodeDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeResponse, error)
		// 获取兑换码列表
		GetRedeemCodeList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeListResponse, error)
		// 更新兑换码
		UpdateRedeemCode(ctx context.Context, in *UpdateRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// 删除兑换码
		DeleteRedeemCode(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
		// 使用兑换码
		UseRedeemCode(ctx context.Context, in *UseRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	}

	defaultRedeemCode struct {
		cli zrpc.Client
	}
)

func NewRedeemCode(cli zrpc.Client) RedeemCode {
	return &defaultRedeemCode{
		cli: cli,
	}
}

// 创建兑换码批次
func (m *defaultRedeemCode) CreateRedeemCodeBatch(ctx context.Context, in *CreateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.CreateRedeemCodeBatch(ctx, in, opts...)
}

// 获取兑换码批次详情
func (m *defaultRedeemCode) RedeemCodeBatchDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeBatchResponse, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.RedeemCodeBatchDetail(ctx, in, opts...)
}

// 获取兑换码批次列表
func (m *defaultRedeemCode) GetRedeemCodeBatchList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeBatchListResponse, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.GetRedeemCodeBatchList(ctx, in, opts...)
}

// 更新兑换码批次
func (m *defaultRedeemCode) UpdateRedeemCodeBatch(ctx context.Context, in *UpdateRedeemCodeBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.UpdateRedeemCodeBatch(ctx, in, opts...)
}

// 删除兑换码批次
func (m *defaultRedeemCode) DeleteRedeemCodeBatch(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.DeleteRedeemCodeBatch(ctx, in, opts...)
}

// 获取兑换码详情
func (m *defaultRedeemCode) RedeemCodeDetail(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*RedeemCodeResponse, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.RedeemCodeDetail(ctx, in, opts...)
}

// 获取兑换码列表
func (m *defaultRedeemCode) GetRedeemCodeList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetRedeemCodeListResponse, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.GetRedeemCodeList(ctx, in, opts...)
}

// 更新兑换码
func (m *defaultRedeemCode) UpdateRedeemCode(ctx context.Context, in *UpdateRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.UpdateRedeemCode(ctx, in, opts...)
}

// 删除兑换码
func (m *defaultRedeemCode) DeleteRedeemCode(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.DeleteRedeemCode(ctx, in, opts...)
}

// 使用兑换码
func (m *defaultRedeemCode) UseRedeemCode(ctx context.Context, in *UseRedeemCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	client := redeemcode.NewRedeemCodeClient(m.cli.Conn())
	return client.UseRedeemCode(ctx, in, opts...)
}
