// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateRedeemCodeBatchRequest struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	UsageLimit  int32  `json:"usage_limit"`
	TotalCount  int32  `json:"total_count"`
	StartedAt   string `json:"started_at"`
	EndedAt     string `json:"ended_at"`
	Status      int32  `json:"status"`
	CreatorId   int64  `json:"creator_id"`
	CreatorName string `json:"creator_name"`
}

type GetRedeemCodeBatchListResponse struct {
	Page     int64                     `json:"page"`
	PageSize int64                     `json:"page_size"`
	Total    int64                     `json:"total"`
	Data     []RedeemCodeBatchResponse `json:"data"`
}

type RedeemCodeBatchResponse struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	UsageLimit  int32  `json:"usage_limit"`
	TotalCount  int32  `json:"total_count"`
	UsedCount   int32  `json:"used_count"`
	StartedAt   string `json:"started_at"`
	EndedAt     string `json:"ended_at"`
	Status      int32  `json:"status"`
	CreatorId   int64  `json:"creator_id"`
	CreatorName string `json:"creator_name"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type UpdateRedeemCodeBatchRequest struct {
	Id          int64  `path:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	StartedAt   string `json:"started_at"`
	EndedAt     string `json:"ended_at"`
	Status      int32  `json:"status"`
}
