// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetRedeemCodeListResponse struct {
	Page     int64                `json:"page"`
	PageSize int64                `json:"page_size"`
	Total    int64                `json:"total"`
	Data     []RedeemCodeResponse `json:"data"`
}

type RedeemCodeResponse struct {
	Id                int64  `json:"id"`
	RedeemCodeBatchId int64  `json:"redeem_code_batch_id"`
	Title             string `json:"title"`
	Value             string `json:"value"`
	UsageLimit        int32  `json:"usage_limit"`
	UsedCount         int32  `json:"used_count"`
	ExpirationAt      string `json:"expiration_at"`
	IsDel             int32  `json:"is_del"`
	DeletedAt         string `json:"deleted_at"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type UpdateRedeemCodeRequest struct {
	Id           int64  `path:"id"`
	Title        string `json:"title"`
	ExpirationAt string `json:"expiration_at"`
	IsDel        int32  `json:"is_del"`
}

type UseRedeemCodeRequest struct {
	RedeemCodeId int64 `json:"redeem_code_id"`
	UserId       int64 `json:"user_id"`
}
