// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetUserListRequest struct {
	Page     int32 `form:"page"`      // 页码
	PageSize int32 `form:"page_size"` // 每页大小
}

type GetUserListResponse struct {
	Page     int32              `json:"page"`      // 页码
	PageSize int32              `json:"page_size"` // 每页大小
	Total    int64              `json:"total"`     // 总记录数
	Data     []UserInfoResponse `json:"data"`      // 用户列表
}

type IDRequest struct {
	Id int64 `path:"id"` // 用户ID
}

type LoginRequest struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	Info  UserInfoResponse `json:"info"`  // 用户信息
	Token string           `json:"token"` // 令牌
}

type RegisterRequest struct {
	Username        string `json:"username"`         // 用户名
	Password        string `json:"password"`         // 密码
	ConfirmPassword string `json:"confirm_password"` // 确认密码
	Nickname        string `json:"nickname"`         // 昵称
	Mobile          string `json:"mobile"`           // 手机号
	Gender          int32  `json:"gender"`           // 性别
	Birthday        string `json:"birthday"`         // 生日
}

type UpdateUserRequest struct {
	Id       int64  `json:"id"`                // 用户ID
	Username string `json:"username,optional"` // 用户名
	Nickname string `json:"nickname,optional"` // 昵称
	Mobile   string `json:"mobile,optional"`   // 手机号
	Gender   int32  `json:"gender,optional"`   // 性别
	Birthday string `json:"birthday,optional"` // 生日
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`       // 用户ID
	Username string `json:"username"` // 用户名
	Nickname string `json:"nickname"` // 昵称
	Mobile   string `json:"mobile"`   // 手机号
	Gender   int32  `json:"gender"`   // 性别
	Birthday string `json:"birthday"` // 生日
}
