// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	redeemcode "github.com/1348453525/user-redeem-code-gozero/api/internal/handler/redeemcode"
	redeemcodebatch "github.com/1348453525/user-redeem-code-gozero/api/internal/handler/redeemcodebatch"
	user "github.com/1348453525/user-redeem-code-gozero/api/internal/handler/user"
	"github.com/1348453525/user-redeem-code-gozero/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/DeleteRedeemCode/:id",
				Handler: redeemcode.DeleteRedeemCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/GetRedeemCodeList",
				Handler: redeemcode.GetRedeemCodeListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/RedeemCodeDetail/:id",
				Handler: redeemcode.RedeemCodeDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/UpdateRedeemCode/:id",
				Handler: redeemcode.UpdateRedeemCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/UseRedeemCode",
				Handler: redeemcode.UseRedeemCodeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/RedeemCode"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/CreateRedeemCodeBatch",
				Handler: redeemcodebatch.CreateRedeemCodeBatchHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/DeleteRedeemCodeBatch/:id",
				Handler: redeemcodebatch.DeleteRedeemCodeBatchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/GetRedeemCodeBatchList/list",
				Handler: redeemcodebatch.GetRedeemCodeBatchListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/RedeemCodeBatchDetail/:id",
				Handler: redeemcodebatch.RedeemCodeBatchDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/UpdateRedeemCodeBatch/:id",
				Handler: redeemcodebatch.UpdateRedeemCodeBatchHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/RedeemCodeBatch"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/Login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/User"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/Delete/:id",
				Handler: user.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/GetList",
				Handler: user.GetListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Info/:id",
				Handler: user.InfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/Update",
				Handler: user.UpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/User"),
	)
}
