// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/1348453525/user-redeem-code-gozero/user-rpc/internal/logic/user"
	"github.com/1348453525/user-redeem-code-gozero/user-rpc/internal/svc"
	"github.com/1348453525/user-redeem-code-gozero/user-rpc/proto/user"
	"google.golang.org/protobuf/types/known/emptypb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.UserInfoResponse, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 登录
func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 获取用户信息
func (s *UserServer) Info(ctx context.Context, in *user.IDRequest) (*user.UserInfoResponse, error) {
	l := userlogic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}

// 获取用户列表
func (s *UserServer) GetList(ctx context.Context, in *user.GetUserListRequest) (*user.GetUserListResponse, error) {
	l := userlogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

// 更新用户信息
func (s *UserServer) Update(ctx context.Context, in *user.UpdateUserRequest) (*emptypb.Empty, error) {
	l := userlogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

// 删除用户
func (s *UserServer) Delete(ctx context.Context, in *user.IDRequest) (*emptypb.Empty, error) {
	l := userlogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
